In [13]:
import pandas as pd
import matplotlib.pyplot as plt
import lasio
import numpy as np

In [20]:
las = lasio.read('ichthys_deep_1_wire_public_2010_sdb.las')

Only engine='normal' can read wrapped files

In [21]:
print(las.curves)

Mnemonic  Unit  Value  Description
--------  ----  -----  -----------
DEPTH     M
AFEC      1/S          =IFC(DEPTH>4962  ""  AFEC)
ANEC      1/S          =IFC(DEPTH>4962  ""  ANEC)
APLC      V/V          =IFC(DEPTH>4962  ""  APLC)
BS        IN           Values changed using TEXT_EDIT
CALI      IN           Values changed using TEXT_EDIT
DENS      G/C3         Merged WIRE_J.RHOM_5 and WIRE_S4R1_EC_ORIG.RHOM_1 at 4854.35
DENSC     G/C3         Merged WIRE_J.DRH_5 and WIRE_S4R1_EC_ORIG.DRH_1 at 4854.35
DRH       G/C3         Merged WIRE_J.DRH_5 and WIRE_S4R1_EC_ORIG.DRH_1 at 4854.35
DT        US/F         =IFC(DEPTH<2450  ""  DTCO_C)
DTCO      US/F         =IFC(DEPTH<2450  ""  DTCO_C)
DTCO_C    US/F         Values changed using TEXT_EDIT
DTSH      US/F         =IFC(DEPTH<2450  ""  DTSM_C)
DTSM_C    US/F         Values changed using TEXT_EDIT  inc casing data
FPLC      V/V          =IFC(DEPTH>4962  ""  FPLC)
GR        GAPI         Merged WIRE_J.GR_J_5 and WIRE_S4R1_EC_ORIG.HSGR_1 at 4837.96
HFK       %            Values changed using TEXT_EDIT
HTHO      PPM          Values changed using TEXT_EDIT
HURA      PPM          Values changed using TEXT_EDIT
NDS       V/V          ND seperation -(((DENS-1.95)/0.05)-((0.45-NEUT)/0.03))
NEUT      V/V          =IFC(DEPTH>4962  ""  APLC)
PEF       B/E          Merged WIRE_J.PEFL_5 and WIRE_S4R1_EC_ORIG.PEFL_1 at 4854.95
PR                     =IFC(DEPTH<2450  ""  PR_C)
PR_C                   Values changed using TEXT_EDIT  inc casing data
RESD      OHMM         Merged WIRE_J.RESD_J_1 and WIRE_PUBLIC_MDB.AT90_1 at 2434.96
RESM      OHMM         Merged WIRE_J.RESM_J_1 and WIRE_PUBLIC_MDB.AT30_1 at 2443.04
RESS      OHMM         3 AIT Two Foot Resistivity A10
RHOM      G/C3         Merged WIRE_J.RHOM_5 and WIRE_S4R1_EC_ORIG.RHOM_1 at 4854.35
SIGF      CU           =IFC(DEPTH>4962  ""  SIGF)
TENS      LBF          Merged WIRE_WORKING.TENS3_1 and WIRE_WORKING.TENS4_1 at 4864.89
VPVS                   =IFC(DEPTH<2450  ""  VPVS_C)
VPVS_C                 Values changed using TEXT_EDIT  inc casing data

In [22]:
sonic_data = las.df().reset_index()

In [9]:
data = las.df()
data.rename_axis('DEPTH').reset_index()

,DEPTH,AFEC,ANEC,APLC,BS,CALI,DENS,DENSC,DRH,DT,...,PR,PR_C,RESD,RESM,RESS,RHOM,SIGF,TENS,VPVS,VPVS_C
0,233.1720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,233.3244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,233.4768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,233.6292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,233.7816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31078,4969.4592,NaN,NaN,NaN,8.5,NaN,2.6681,0.111585,0.111585,NaN,...,NaN,NaN,NaN,NaN,NaN,2.6681,NaN,5213.0,NaN,NaN
31079,4969.6116,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5205.0,NaN,NaN
31080,4969.7640,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31081,4969.9164,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31082,4970.0688,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df_4=lasio.read('ichthys_deep_1_wire_public_2010_sdb.LAS').df().reset_index()
df_4

td =4074.5
bd = 4242.9
vp=df_4['DTCO'].to_numpy()[np.where(np.logical_and(df_4['DEPTH'].to_numpy()>=td,df_4['DEPTH'].to_numpy()<=bd))]
vs=df_4['DTSH'].to_numpy()[np.where(np.logical_and(df_4['DEPTH'].to_numpy()>=td,df_4['DEPTH'].to_numpy()<=bd))]
por=df_4['APLC'].to_numpy()[np.where(np.logical_and(df_4['DEPTH'].to_numpy()>=td,df_4['DEPTH'].to_numpy()<=bd))]
plt.figure(figsize=(3,10))
vp_corrected=304800/vp
vs_corrected=304800/vs
plt.plot(vp_corrected,depth)
plt.plot(vs_corrected,depth)

Only engine='normal' can read wrapped files

NameError: name 'depth' is not defined

In [16]:
df_4=lasio.read('ichthys_deep_1_wire_public_2010_sdb.LAS').df().reset_index()
df_4

Only engine='normal' can read wrapped files

,DEPTH,AFEC,ANEC,APLC,BS,CALI,DENS,DENSC,DRH,DT,...,PR,PR_C,RESD,RESM,RESS,RHOM,SIGF,TENS,VPVS,VPVS_C
0,233.1720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,233.3244,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,233.4768,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,233.6292,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,233.7816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31078,4969.4592,NaN,NaN,NaN,8.5,NaN,2.6681,0.111585,0.111585,NaN,...,NaN,NaN,NaN,NaN,NaN,2.6681,NaN,5213.0,NaN,NaN
31079,4969.6116,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5205.0,NaN,NaN
31080,4969.7640,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31081,4969.9164,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31082,4970.0688,NaN,NaN,NaN,8.5,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
df_4['DEPTH']

0         233.1720
1         233.3244
2         233.4768
3         233.6292
4         233.7816
           ...
31078    4969.4592
31079    4969.6116
31080    4969.7640
31081    4969.9164
31082    4970.0688
Name: DEPTH, Length: 31083, dtype: float64